
import React, { FormEvent, useState } from "react";
import { CheckCircle2Icon, MailIcon, MapPinIcon, PhoneIcon } from "lucide-react";

export function ContactSection() {
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => {event.preventDefault();setSubmitted(true);};

  return <section id="contact" className="bg-stone-50 px-6 py-28 sm:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2 lg:gap-20"><div><p className="text-[11px] font-bold uppercase tracking-[0.17em] text-[#92400e]">Get in touch</p><h2 className="mt-3 font-serif text-5xl tracking-[-0.045em] sm:text-6xl">Let’s talk about your project.</h2><p className="mt-8 max-w-xl leading-7 text-stone-500">Tell us what you need. We will help you choose the best way to build it.</p><div className="mt-10 space-y-5"><ContactDetail icon={MapPinIcon} title="Johannesburg, South Africa" text="We work with clients anywhere." /><ContactDetail icon={MailIcon} title="lukulurecordings@gmail.com" text="Send us an email." href="mailto:lukulurecordings@gmail.com" /><ContactDetail icon={PhoneIcon} title="+27 73 093 3554" text="Call us." href="tel:+27730933554" /></div></div><div className="rounded-[2rem] border border-stone-100 bg-white p-7 shadow-[0_20px_50px_rgba(26,24,23,0.08)] sm:p-10"><h3 className="font-serif text-3xl">Ask for a quote</h3>{submitted ? <div className="mt-8 rounded-2xl bg-[#f8eddd] p-7 text-center"><CheckCircle2Icon className="mx-auto text-[#92400e]" size={32} /><h4 className="mt-4 font-serif text-2xl">Thanks for getting in touch</h4><p className="mt-2 text-sm leading-6 text-stone-600">We will reply within 24 hours.</p><button type="button" className="mt-5 text-sm font-bold text-[#92400e] underline" onClick={() => setSubmitted(false)}>Send another message</button></div> : <form className="mt-8 space-y-5" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" placeholder="Your name" required /><Field label="Email" placeholder="you@example.com" type="email" required /></div><label className="block"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-stone-400">What do you need?</span><select className="mt-2 w-full rounded-xl border-0 bg-stone-50 p-4 text-sm text-stone-700 ring-1 ring-transparent outline-none transition focus:ring-[#c28d4b]"><option>Website</option><option>Business website</option><option>Custom tool</option><option>Something else</option></select></label><label className="block"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-stone-400">Your project</span><textarea className="mt-2 min-h-32 w-full resize-y rounded-xl border-0 bg-stone-50 p-4 text-sm text-stone-700 ring-1 ring-transparent outline-none transition placeholder:text-stone-400 focus:ring-[#c28d4b]" placeholder="Tell us a little about it..." required /></label><button className="w-full rounded-xl bg-[#1a1817] py-4 text-sm font-bold text-white transition-colors hover:bg-[#92400e]" type="submit">Send message</button></form>}</div></div></section>;
}

function ContactDetail({ icon: Icon, title, text, href }: {icon: typeof MapPinIcon;title: string;text: string;href?: string;}) {const content = <><h3 className="font-bold text-[#1a1817]">{title}</h3><p className="mt-0.5 text-sm text-stone-500">{text}</p></>;return <div className="flex items-center gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-white text-[#92400e] shadow-sm"><Icon size={20} /></span>{href ? <a className="transition-opacity hover:opacity-70" href={href}>{content}</a> : <div>{content}</div>}</div>;}
function Field({ label, placeholder, type = "text", required = false }: {label: string;placeholder: string;type?: string;required?: boolean;}) {return <label className="block"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-stone-400">{label}</span><input className="mt-2 w-full rounded-xl border-0 bg-stone-50 p-4 text-sm text-stone-700 ring-1 ring-transparent outline-none transition placeholder:text-stone-400 focus:ring-[#c28d4b]" type={type} placeholder={placeholder} required={required} /></label>;}