
import React from "react";
import { CheckIcon } from "lucide-react";
import { motion } from "framer-motion";

const suites = [
{ eyebrow: "For creatives", title: "The Creator", copy: "A clean website for artists, musicians, and small personal brands.", items: ["Show your work", "Add social and music links", "Fast website setup"], recommended: false },
{ eyebrow: "For businesses", title: "Small Business", copy: "A full website that helps customers learn about you and get in touch.", items: ["Five or more pages", "Easy website updates", "Google and Maps setup", "Chat button"], recommended: true },
{ eyebrow: "For custom needs", title: "Custom Tools", copy: "A private tool or dashboard made to fit the way your business works.", items: ["Safe data storage", "Payments and other connections", "Private customer login"], recommended: false }];


export function ServicesSection() {return <section id="services" className="bg-stone-50 px-6 py-28 sm:py-32"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-[11px] font-bold uppercase tracking-[0.17em] text-[#92400e]">What we offer</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em] sm:text-6xl">Choose what fits your business</h2><p className="mt-5 leading-7 text-stone-500">We offer three simple ways to get your business online and working better.</p></div><div className="mt-16 grid gap-7 lg:grid-cols-3">{suites.map((suite, index) => <SuiteCard key={suite.title} suite={suite} index={index} />)}</div><div className="mt-20 grid items-center gap-12 border-t border-stone-200 pt-12 lg:grid-cols-[.85fr_1.15fr]"><div><h3 className="font-serif text-3xl">What each service covers</h3><p className="mt-4 max-w-md text-sm leading-6 text-stone-500">Each option is built for a different need. We will help you choose the right one.</p><div className="mt-6 flex flex-wrap gap-4 text-[10px] font-bold uppercase tracking-[0.12em]"><Legend color="bg-[#c28d4b]" label="Creator" /><Legend color="bg-[#1a1817]" label="Business" /><Legend color="bg-[#92400e]" label="Custom" /></div></div><CapabilityGraphic /></div></div></section>;}
function SuiteCard({ suite, index }: {suite: (typeof suites)[number];index: number;}) {return <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ delay: index * 0.08 }} className={`relative flex min-h-[485px] flex-col overflow-hidden rounded-[2rem] border bg-white p-8 sm:p-10 ${suite.recommended ? "border-2 border-[#1a1817] shadow-[0_20px_48px_rgba(26,24,23,0.12)]" : "border-stone-200"}`}>{suite.recommended && <span className="absolute right-7 top-0 -translate-y-1/2 rounded-full bg-[#c28d4b] px-4 py-1.5 text-[10px] font-bold uppercase tracking-[0.08em] text-white">Popular choice</span>}<p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#b47732]">{suite.eyebrow}</p><h3 className="mt-5 font-serif text-3xl">{suite.title}</h3><p className="mt-4 text-sm leading-6 text-stone-500">{suite.copy}</p><ul className="mt-7 space-y-4">{suite.items.map((item) => <li className="flex gap-3 text-sm font-semibold text-stone-800" key={item}><CheckIcon className="mt-0.5 shrink-0 text-[#c28d4b]" size={16} strokeWidth={3} />{item}</li>)}</ul><a className="mt-auto block rounded-xl bg-[#1a1817] py-4 text-center text-sm font-bold text-white transition-colors hover:bg-[#92400e]" href="#contact">Ask for a quote</a></motion.article>;}
function Legend({ color, label }: {color: string;label: string;}) {return <span className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${color}`} />{label}</span>;}
function CapabilityGraphic() {const points = ["50,11 77,27 79,62 50,82 20,62 23,27", "50,19 73,32 73,59 50,75 27,59 27,32", "50,25 68,34 70,57 50,67 31,56 31,35"];return <div className="mx-auto w-full max-w-xl"><div className="relative aspect-[1.6/1] overflow-hidden rounded-3xl border border-stone-200 bg-white p-6"><svg viewBox="0 0 100 90" className="h-full w-full" aria-label="Service comparison" role="img"><g fill="none" stroke="#e7e3dd" strokeWidth=".5"><polygon points="50,9 80,26 80,61 50,80 20,61 20,26" /><polygon points="50,20 71,32 71,56 50,68 29,56 29,32" /><line x1="50" y1="9" x2="50" y2="80" /><line x1="20" y1="26" x2="80" y2="61" /><line x1="80" y1="26" x2="20" y2="61" /></g><polygon points={points[0]} fill="rgba(194,141,75,.14)" stroke="#c28d4b" strokeWidth="1.2" /><polygon points={points[1]} fill="rgba(26,24,23,.08)" stroke="#1a1817" strokeWidth="1.2" /><polygon points={points[2]} fill="rgba(146,64,14,.11)" stroke="#92400e" strokeWidth="1.2" /></svg></div></div>;}