import { useMemo, useState } from "react";
import { ArrowLeftIcon, ArrowRightIcon, CheckIcon, MailIcon, RotateCcwIcon } from "lucide-react";
import { Budget, calculateRecommendation, Feature, featureOptions, formatRand, goalLabels, Goal, SmartFormAnswers } from "./pricing";

const initialAnswers: SmartFormAnswers = { goal: "", budget: "", features: [] };
const budgetOptions: Array<{ id: Budget; label: string; detail: string }> = [
  { id: "starter", label: "R800 – R2,000", detail: "A focused start with the essentials" },
  { id: "growth", label: "R2,000 – R5,000", detail: "More pages, conversion tools and polish" },
  { id: "premium", label: "R5,000+", detail: "Commerce or a more advanced business system" },
];
const steps = ["Goal", "Budget", "Features", "Your plan"];

export function SmartForm() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<SmartFormAnswers>(initialAnswers);
  const result = useMemo(() => calculateRecommendation(answers), [answers]);
  const canContinue = step === 0 ? Boolean(answers.goal) : step === 1 ? Boolean(answers.budget) : true;

  const selectGoal = (goal: Goal) => setAnswers((current) => ({ ...current, goal }));
  const selectBudget = (budget: Budget) => setAnswers((current) => ({ ...current, budget }));
  const toggleFeature = (feature: Feature) => setAnswers((current) => ({ ...current, features: current.features.includes(feature) ? current.features.filter((item) => item !== feature) : [...current.features, feature] }));
  const selectedFeatures = result.effectiveFeatures.map((id) => featureOptions.find((feature) => feature.id === id)).filter(Boolean);
  const emailBody = encodeURIComponent(`Hello Lukulu,\n\nI completed the smart project planner.\n\nGoal: ${answers.goal ? goalLabels[answers.goal] : "Not selected"}\nBudget: ${budgetOptions.find((item) => item.id === answers.budget)?.label ?? "Not selected"}\nRecommended package: ${result.packageName}\nFeatures: ${selectedFeatures.map((item) => item?.label).join(", ") || "Core one-page website"}\nEstimated starting price: ${formatRand(result.total)}\n\nPlease contact me to confirm the scope.`);

  return <section id="estimator" className="relative overflow-hidden bg-[#1a1817] px-5 py-24 text-white sm:px-6 sm:py-32">
    <div className="pointer-events-none absolute -right-32 top-12 h-80 w-80 rounded-full bg-[#c28d4b]/15 blur-[90px]" />
    <div className="relative mx-auto max-w-7xl">
      <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e5ba78]">Smart project planner</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-[-.04em] sm:text-6xl">Build a clear website estimate in four small steps.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-300">Choose what your business needs. Your estimate starts at R800 and updates as the project grows.</p></div>
      <div className="mt-12 grid overflow-hidden rounded-[2rem] border border-white/10 bg-[#22201f] shadow-2xl lg:grid-cols-[1fr_330px]">
        <div className="p-6 sm:p-10 lg:p-12">
          <ol className="mb-12 grid grid-cols-4 gap-2" aria-label="Estimator progress">{steps.map((label, index) => <li key={label}><div className={`h-1.5 rounded-full ${index <= step ? "bg-[#e5ba78]" : "bg-white/10"}`} /><span className={`mt-2 hidden text-xs font-bold sm:block ${index === step ? "text-white" : "text-stone-500"}`}>{index + 1}. {label}</span></li>)}</ol>
          <div className="min-h-[390px]" aria-live="polite">
            {step === 0 && <Step title="What should your website do first?" hint="Choose the result that matters most right now."><ChoiceGrid>{(Object.keys(goalLabels) as Goal[]).map((goal) => <Choice key={goal} selected={answers.goal === goal} onClick={() => selectGoal(goal)} title={goalLabels[goal]} />)}</ChoiceGrid></Step>}
            {step === 1 && <Step title="What investment range feels right?" hint="This guides the package—not a final commitment."><ChoiceGrid>{budgetOptions.map((budget) => <Choice key={budget.id} selected={answers.budget === budget.id} onClick={() => selectBudget(budget.id)} title={budget.label} detail={budget.detail} />)}</ChoiceGrid></Step>}
            {step === 2 && <Step title="Which capabilities do you need?" hint="Select any that apply. You can change these later."><div className="grid gap-3 sm:grid-cols-2">{featureOptions.map((feature) => { const selected = answers.features.includes(feature.id); return <button key={feature.id} type="button" aria-pressed={selected} onClick={() => toggleFeature(feature.id)} className={`flex min-h-28 items-start gap-4 rounded-2xl border p-5 text-left transition focus:outline-none focus:ring-2 focus:ring-[#e5ba78] ${selected ? "border-[#e5ba78] bg-[#e5ba78]/10" : "border-white/10 bg-white/[.03] hover:border-white/25"}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md border ${selected ? "border-[#e5ba78] bg-[#e5ba78] text-[#1a1817]" : "border-stone-600"}`}>{selected && <CheckIcon size={15} />}</span><span><strong className="block text-base">{feature.label} <em className="ml-1 not-italic text-[#e5ba78]">+{formatRand(feature.cost)}</em></strong><small className="mt-1 block text-sm leading-6 text-stone-400">{feature.description}</small></span></button>; })}</div></Step>}
            {step === 3 && <Step title={`${result.packageName} is the right starting point.`} hint="This is a transparent guide. We confirm the exact scope before work begins."><div className="rounded-2xl bg-white p-6 text-[#1a1817] sm:p-8"><div className="flex flex-col gap-5 border-b border-stone-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#92400e]">Recommended package</p><h3 className="mt-2 font-serif text-4xl">{result.packageName}</h3></div><div className="sm:text-right"><span className="text-sm text-stone-500">Estimated from</span><strong className="block font-serif text-4xl text-[#92400e]">{formatRand(result.total)}</strong></div></div><ul className="mt-6 grid gap-3 sm:grid-cols-2"><li className="flex gap-2 text-sm"><CheckIcon className="text-[#92400e]" size={18} />Responsive core website</li>{selectedFeatures.map((feature) => <li key={feature?.id} className="flex gap-2 text-sm"><CheckIcon className="text-[#92400e]" size={18} />{feature?.label}</li>)}</ul><a className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-[#92400e] px-6 py-4 text-base font-bold text-white hover:bg-[#78350f]" href={`mailto:lukulurecordings@gmail.com?subject=${encodeURIComponent(`Project estimate: ${result.packageName}`)}&body=${emailBody}`}><MailIcon size={19} />Email my project brief</a></div></Step>}
          </div>
          <div className="mt-8 flex items-center justify-between gap-4 border-t border-white/10 pt-6">{step > 0 ? <button type="button" onClick={() => setStep((value) => value - 1)} className="inline-flex items-center gap-2 rounded-xl px-4 py-3 font-bold text-stone-300 hover:bg-white/5"><ArrowLeftIcon size={18} />Back</button> : <button type="button" onClick={() => { setAnswers(initialAnswers); setStep(0); }} className="inline-flex items-center gap-2 px-2 py-3 text-sm font-bold text-stone-500"><RotateCcwIcon size={16} />Reset</button>}{step < 3 && <button type="button" disabled={!canContinue} onClick={() => setStep((value) => value + 1)} className="inline-flex items-center gap-2 rounded-xl bg-[#e5ba78] px-6 py-3.5 font-bold text-[#1a1817] disabled:cursor-not-allowed disabled:opacity-35">Continue<ArrowRightIcon size={18} /></button>}</div>
        </div>
        <aside className="border-t border-white/10 bg-[#171615] p-7 lg:border-l lg:border-t-0 lg:p-9" aria-label="Live estimate"><p className="text-xs font-bold uppercase tracking-[.16em] text-stone-500">Live estimate</p><div className="mt-6 border-y border-dashed border-stone-700 py-6"><span className="text-sm text-stone-400">Starting total</span><strong className="mt-1 block font-serif text-5xl text-[#e5ba78]">{formatRand(result.total)}</strong></div><dl className="mt-6 space-y-4 text-sm"><PriceRow label="Core website" value={result.base} />{answers.goal && answers.goal !== "launch" && <PriceRow label="Goal adjustment" value={result.total - result.base - answers.features.reduce((sum, id) => sum + (featureOptions.find((f) => f.id === id)?.cost ?? 0), 0)} />}{answers.features.map((id) => { const item = featureOptions.find((feature) => feature.id === id); return item ? <PriceRow key={id} label={item.label} value={item.cost} /> : null; })}</dl><p className="mt-8 text-xs leading-6 text-stone-500">Estimated starting price in South African rand. Final pricing depends on content, integrations and timeline.</p></aside>
      </div>
    </div>
  </section>;
}

function Step({ title, hint, children }: { title: string; hint: string; children: React.ReactNode }) { return <div><p className="text-sm font-bold text-[#e5ba78]">Question</p><h3 className="mt-2 max-w-2xl font-serif text-3xl leading-tight sm:text-4xl">{title}</h3><p className="mb-8 mt-3 text-base leading-7 text-stone-400">{hint}</p>{children}</div>; }
function ChoiceGrid({ children }: { children: React.ReactNode }) { return <div className="grid gap-3 sm:grid-cols-2">{children}</div>; }
function Choice({ selected, onClick, title, detail }: { selected: boolean; onClick: () => void; title: string; detail?: string }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={`min-h-28 rounded-2xl border p-5 text-left transition focus:outline-none focus:ring-2 focus:ring-[#e5ba78] ${selected ? "border-[#e5ba78] bg-[#e5ba78]/10" : "border-white/10 bg-white/[.03] hover:border-white/25"}`}><span className="flex items-start justify-between gap-3"><strong className="text-lg leading-7">{title}</strong>{selected && <CheckIcon className="shrink-0 text-[#e5ba78]" size={20} />}</span>{detail && <small className="mt-2 block text-sm leading-6 text-stone-400">{detail}</small>}</button>; }
function PriceRow({ label, value }: { label: string; value: number }) { return <div className="flex justify-between gap-4"><dt className="text-stone-400">{label}</dt><dd className="font-bold">{formatRand(value)}</dd></div>; }
