
import React from "react";
import { FileTextIcon, Music2Icon, PackageIcon } from "lucide-react";

const tools = [
{ label: "Invoices", icon: FileTextIcon, title: "Send invoices", copy: "Create quotes and invoices from one simple place.", style: "bg-[#1a1817] text-white border-[#1a1817]", muted: "bg-white/10", detail: "bg-white/5 border-white/10" },
{ label: "Stock", icon: PackageIcon, title: "Manage stock", copy: "See your stock and sales anytime, on any device.", style: "bg-stone-50 text-[#1a1817] border-stone-200", muted: "bg-stone-900/5", detail: "bg-white border-stone-100" },
{ label: "Press kit", icon: Music2Icon, title: "Artist pages", copy: "Share your music and details with bookers and festivals.", style: "bg-[#faeedb] text-[#1a1817] border-[#ebcca0]", muted: "bg-[#92400e]/10", detail: "bg-white border-[#f0d9b8]" }];

export function ToolsSection() {return <section id="tools" className="px-6 py-28 sm:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.17em] text-[#92400e]">More than a website</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em] sm:text-5xl">Tools for daily work</h2><p className="mt-5 leading-7 text-stone-500">We can build simple tools that save you time every day.</p></div><div className="mt-14 grid gap-7 md:grid-cols-3">{tools.map((tool) => <ToolCard key={tool.title} tool={tool} />)}</div></div></section>;}
function ToolCard({ tool }: {tool: (typeof tools)[number];}) {const Icon = tool.icon;return <article className={`flex min-h-[340px] flex-col rounded-3xl border p-7 ${tool.style}`}><div className="flex items-center justify-between"><span className={`rounded-lg px-2.5 py-2 text-[10px] font-bold uppercase tracking-[.08em] ${tool.muted}`}>{tool.label}</span><span className={`flex h-9 w-9 items-center justify-center rounded-full border ${tool.style.includes("text-white") ? "border-white/20" : "border-current/15"}`}><Icon size={16} /></span></div><div className={`mt-9 rounded-xl border p-4 ${tool.detail}`}><div className="flex items-center justify-between border-b border-current/10 pb-3"><span className="h-2 w-20 rounded bg-current/15" /><span className="h-2 w-9 rounded bg-[#c28d4b]" /></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="h-12 rounded-lg bg-current/[.06]" /><div className="h-12 rounded-lg bg-current/[.06]" /></div></div><h3 className="mt-7 font-serif text-2xl">{tool.title}</h3><p className={`mt-2 text-sm leading-6 ${tool.style.includes("text-white") ? "text-stone-400" : "text-stone-500"}`}>{tool.copy}</p></article>;}